name: ci

on:
  push:

jobs:
  build1:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    env:
      CI: 1
      RAILS_ENV: test
    services:
      postgres:
        image: postgres:16.4-alpine
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
        env:
          POSTGRES_PASSWORD: password
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          working-directory: ./backend
      - run: bin/rubocop -f github
        working-directory: ./backend
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: ./frontend/package-lock.json
      - run: |
          npm i @rollup/rollup-linux-x64-gnu
          npm ci
          git diff || true
          npm run graphql-codegen
          npm run build:move
        shell: bash
        working-directory: ./frontend
