name: ci

on:
  push:

jobs:
  build1:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    env:
      CI: 1
      RAILS_ENV: test
    services:
      postgres:
        image: postgres:16.4-alpine
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
        env:
          POSTGRES_PASSWORD: password
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          working-directory: ./backend
      - uses: pnpm/action-setup@v4
        with:
          package_json_file: ./frontend/package.json
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
          cache-dependency-path: ./frontend/pnpm-lock.yaml
      - run: pnpm i
        working-directory: ./frontend
      - run: |
          npm run graphql-codegen
          npm run build:move
        shell: bash
        working-directory: ./frontend
      - run: bundle exec rails db:prepare
        working-directory: ./backend
      - run: bundle exec rspec
        working-directory: ./backend
  build2:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: ./backend
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          working-directory: ./backend
      - run: bin/rubocop -f github
      - run: bundle exec rbs collection install
      - run: bundle exec steep check
